---
abstract: 'A plugin to display all the POD in your local lib.'
author:
  - 'Steven Humphrey <catchperlmodules@33k.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-POD
version: 0.001
